/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121789-gddf443f1e9-20251117"
#endif /* AVUTIL_FFVERSION_H */
